boar/distributor/forms.py
from flask_wtf import FlaskForm
from wtforms import SelectField, StringField, SubmitField
from wtforms.validators import InputRequired


class DistributorForm(FlaskForm):
    states = [('AK', 'Alaska'), ('AL', 'Alabama'), ('AR', 'Arkansas'),
              ('AZ', 'Arizona'), ('CA', 'California'), ('CO', 'Colorado'),
              ('CT', 'Connecticut'), ('DC', 'District of Columbia'),
              ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'),
              ('HI', 'Hawaii'), ('IA', 'Iowa'), ('ID', 'Idaho'),
              ('IL', 'Illinois'), ('IN', 'Indiana'), ('KS', 'Kansas'),
              ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('MA', 'Massachusetts'),
              ('MD', 'Maryland'), ('ME', 'Maine'), ('MI', 'Michigan'),
              ('MN', 'Minnesota'), ('MO', 'Missouri'), ('MS', 'Mississippi'),
              ('MT', 'Montana'), ('NC', 'North Carolina'),
              ('ND', 'North Dakota'), ('NE', 'Nebraska'),
              ('NH', 'New Hampshire'), ('NJ', 'New Jersey'),
              ('NM', 'New Mexico'), ('NV', 'Nevada'), ('NY', 'New York'),
              ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'),
              ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'),
              ('SC', 'South Carolina'), ('SD', 'South Dakota'),
              ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'),
              ('VA', 'Virginia'), ('VT', 'Vermont'), ('WA', 'Washington'),
              ('WI', 'Wisconsin'), ('WV', 'West Virginia'), ('WY', 'Wyoming')]

    company = StringField('Company', validators=[InputRequired()])
    payee = StringField('Payee', validators=[InputRequired()])
    address1 = StringField('Address 1', validators=[InputRequired()])
    address2 = StringField('Address 2')
    city = StringField('City', validators=[InputRequired()])
    state = SelectField('State', choices=states)
    zip = StringField('Zip', validators=[InputRequired()])
    submit = SubmitField('Submit')

boar/distributor/routes.py
# routes for distributors

from flask import Blueprint, flash, render_template, redirect, url_for
from flask_login import login_required, current_user
from boar import db
from boar.models import Distributor
from boar.distributor.forms import DistributorForm

distributors_bp = Blueprint('distributors_bp', __name__)


@distributors_bp.route('/distributor/new', methods=['GET', 'POST'])
@login_required
def new_distributor():
    """
    Add a new distributor
    """
    form = DistributorForm()
    if form.validate_on_submit():
        distributor = Distributor(company=form.company.data,
                                  payee=form.payee.data,
                                  address1=form.address1.data,
                                  address2=form.address2.data,
                                  city=form.city.data,
                                  state=form.state.data,
                                  zip=form.zip.data,
                                  organization_id=current_user.organization_id)
        db.session.add(distributor)
        db.session.commit()
        flash('Distributor added successfully.', 'success')
        return redirect(url_for('distributors_bp.list_distributors'))
    return render_template('/distributors/new_distributor.html', form=form,
                           title='New Distributor', heading='New Distributor')


@distributors_bp.route('/distributor/update/<int:id>', methods=['GET', 'POST'])
@login_required
def update_distributor(id):
    """
    Updates a distributor
    """
    distributor = Distributor.query.filter_by(
        id=id, organization_id=current_user.organization_id).first_or_404()
    form = DistributorForm(obj=distributor)
    if form.validate_on_submit():
        form.populate_obj(distributor)
        db.session.commit()
        flash('Distributor successfully updated.', 'success')
        return redirect(url_for('main.index'))
    return render_template('/distributors/new_distributor.html', form=form,
                           title='Edit Distributor',
                           heading='Edit Distributor')


@distributors_bp.route('/distributor/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_distributor(id):
    """
    Deletes a distributor
    """
    distributor = Distributor.query.filter_by(id=id).first()
    db.session.delete(distributor)
    db.session.commit()
    flash('Distributor successfully deleted.', 'success')
    return redirect(url_for('distributors_bp.list_distributors'))


@distributors_bp.route('/distributors')
@login_required
def list_distributors():
    distributors = Distributor.query.order_by(Distributor.company).filter_by(
         organization_id=current_user.organization_id).all()
    if not distributors:
        flash('No distributors found.', 'warning')
        return redirect(url_for('main.index'))
    else:
        return render_template('/distributors/distributor_table.html',
                               distributors=distributors, title='Distributors',
                               heading='Distributors')

boar/distributor/views.py
# views for distributors

from boar import app, db
from flask import flash, render_template, redirect, url_for
from flask_login import login_required, current_user
from ..models import Distributor
from .forms import DistributorForm
from ..tables import Distributors


@app.route('/distributor/new', methods=['GET', 'POST'])
@login_required
def new_distributor():
    """
    Add a new distributor
    """
    form = DistributorForm()
    if form.validate_on_submit():
        distributor = Distributor(company=form.company.data,
                                  payee=form.payee.data,
                                  address1=form.address1.data,
                                  address2=form.address2.data,
                                  city=form.city.data,
                                  state=form.state.data,
                                  zip=form.zip.data,
                                  organization_id=current_user.organization_id)
        db.session.add(distributor)
        db.session.commit()
        flash('Distributor added successfully!')
        return redirect(url_for('index'))
    return render_template('/distributor/distributor.html', form=form,
                           title='New Distributor', heading='New Distributor')


@app.route('/distributors')
@login_required
def list_distributors():
    distributors = Distributor.query.order_by(Distributor.company).filter(
         Distributor.organization_id == current_user.organization_id).all()
    if not distributors:
        flash('No distributors found!')
        return redirect(url_for('index'))
    else:
        table = Distributors(distributors)
        return render_template('/distributor/distributor_table.html',
                               table=table, title='Distributors',
                               heading='Distributors',
                               distributors=distributors)


@app.route('/distributor/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_distributor(id):
    distributor = Distributor.query.filter(
        Distributor.id == id,
        Distributor.organization_id == current_user.organization_id).first()
    form = DistributorForm(obj=distributor)
    if form.validate_on_submit():
        distributor.company = form.company.data
        distributor.payee = form.payee.data
        distributor.address1 = form.address1.data
        distributor.address2 = form.address2.data
        distributor.city = form.city.data
        distributor.state = form.state.data
        distributor.zip = form.zip.data
        db.session.commit()
        flash('Distributor updated successfully!')
        return redirect(url_for('index'))
    return render_template('/distributor/distributor.html', form=form,
                           title='Edit Distributor',
                           heading='Edit Distributor')


@app.route('/distributor/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_distributor(id):
    """
    Delete the item in the database that matches the specified ID in the URL
    """
    distributor = Distributor.query.filter(Distributor.id == id).first()
    db.session.delete(distributor)
    db.session.commit()
    flash('Distributor successfully deleted!')
    return redirect(url_for('list_distributors'))

boar/views/distributor.py
# distributor.py

from boar import app, db
from flask import flash, render_template, redirect, url_for
from flask_login import login_required, current_user
from ..models import Distributor
from ..forms import DistributorForm
from ..tables import Distributors


@app.route('/distributor/new', methods=['GET', 'POST'])
@login_required
def new_distributor():
    """
    Add a new distributor
    """
    form = DistributorForm()
    if form.validate_on_submit():
        distributor = Distributor(company=form.company.data,
                                  payee=form.payee.data,
                                  address1=form.address1.data,
                                  address2=form.address2.data,
                                  city=form.city.data,
                                  state=form.state.data,
                                  zip=form.zip.data,
                                  organization_id=current_user.organization_id)
        db.session.add(distributor)
        db.session.commit()
        flash('Distributor added successfully!')
        return redirect(url_for('index'))
    return render_template('/forms/distributor.html', form=form,
                           title='New Distributor', heading='New Distributor')


@app.route('/distributors')
@login_required
def list_distributors():
    distributors = Distributor.query.order_by(Distributor.company).filter(
         Distributor.organization_id == current_user.organization_id).all()
    if not distributors:
        flash('No distributors found!')
        return redirect(url_for('index'))
    else:
        table = Distributors(distributors)
        return render_template('/distributor_table.html', table=table,
                               title='Distributors', heading='Distributors',
                               distributors=distributors)


@app.route('/distributor/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_distributor(id):
    distributor = Distributor.query.filter(
        Distributor.id == id,
        Distributor.organization_id == current_user.organization_id).first()
    form = DistributorForm(obj=distributor)
    if form.validate_on_submit():
        distributor.company = form.company.data
        distributor.payee = form.payee.data
        distributor.address1 = form.address1.data
        distributor.address2 = form.address2.data
        distributor.city = form.city.data
        distributor.state = form.state.data
        distributor.zip = form.zip.data
        db.session.commit()
        flash('Distributor updated successfully!')
        return redirect(url_for('index'))
    return render_template('/forms/distributor.html', form=form,
                           title='Edit Distributor',
                           heading='Edit Distributor')


@app.route('/distributor/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_distributor(id):
    """
    Delete the item in the database that matches the specified ID in the URL
    """
    distributor = Distributor.query.filter(Distributor.id == id).first()
    db.session.delete(distributor)
    db.session.commit()
    flash('Distributor successfully deleted!')
    return redirect(url_for('list_distributors'))

boar/templates/distributors/distributor_table.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<h1>{% block heading %}{{ heading }}{% endblock %}</h1>
<div class="content-section">
  <table id="distributors_table" class="table table-hover">
  <thead>
      <tr>
          <th>Company</th>
          <th>Payee</th>
          <th>Address Line 1</th>
          <th>Address Line 2</th>
          <th>City</th>
          <th>State</th>
          <th>Zip</th>
          <th>Update</th>
          <th>Delete</th>
      </tr>
  </thead>
  <tbody>
    {% for distributor in distributors %}
      <tr>
          <td style="padding: 15px; text-align: left;">{{ distributor.company }}</td>
          <td style="padding: 15px; text-align: left;">{{ distributor.payee }}</td>
          <td style="padding: 15px; text-align: left;">{{ distributor.address1 }}</td>
          <td style="padding: 15px; text-align: left;">{{ distributor.address2 }}</td>
          <td style="padding: 15px; text-align: left;">{{ distributor.city }}</td>
          <td style="padding: 15px; text-align: left;">{{ distributor.state }}</td>
          <td style="padding: 15px; text-align: left;">{{ distributor.zip }}</td>
          <td style="padding: 15px; text-align: left;"><a href="{{ url_for('distributors_bp.update_distributor', id=distributor.id) }}" class="table-link">Update</a></td>
          <td style="padding: 15px; text-align: left;"><a href="{{ url_for('distributors_bp.delete_distributor', id=distributor.id) }}" class="table-link">Delete</a></td>
          </td>
      </tr>
    {% endfor %}
  </tbody>
  </table>
</div>
{% endblock content %}

boar/templates/distributors/new_distributor.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">{% block heading %}{{ heading }}{% endblock %}</legend>
        <div class="form-group">
          {{ form.company.label(class="form-control-label") }}
          {{ form.company(class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.payee.label(class="form-control-label") }}
          {{ form.payee(class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.address1.label(class="form-control-label") }}
          {{ form.address1(class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.address2.label(class="form-control-label") }}
          {{ form.address2(class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.city.label(class="form-control-label") }}
          {{ form.city(class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.state.label(class="form-control-label") }}
          {{ form.state(class="form-control") }}
        </div>
        <div class="form-group">
          {{ form.zip.label(class="form-control-label") }}
          {{ form.zip(class="form-control") }}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
  </div>
{% endblock content %}