boar/program/forms.py
# forms for programs

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import InputRequired


class ProgramForm(FlaskForm):
    name = StringField('Name', validators=[InputRequired()])
    submit = SubmitField('Submit')

boar/program/routes.py
# routes for programs

from flask import Blueprint, flash, render_template, redirect, url_for
from flask_login import login_required, current_user
from boar import db
from boar.models import Program
from boar.program.forms import ProgramForm

programs_bp = Blueprint('programs_bp', __name__)


@programs_bp.route('/program/new', methods=['GET', 'POST'])
@login_required
def new_program():
    """
    Add a new program
    """
    form = ProgramForm()
    if form.validate_on_submit():
        program = Program(name=form.name.data,
                          organization_id=current_user.organization_id)
        db.session.add(program)
        db.session.commit()
        flash('Program added successfully!')
        return redirect(url_for('main.index'))
    return render_template('/programs/new_program.html', form=form,
                           title='New Program', heading='New Program')


@programs_bp.route('/programs', methods=['GET', 'POST'])
@login_required
def view_programs():
    """
    Displays a table with all active programs.
    """
    programs = Program.query.order_by(Program.name).filter_by(
        organization_id=current_user.organization_id).all()
    if not programs:
        flash('No programs found.', 'warning')
        return redirect(url_for('main.index'))
    else:
        return render_template('/programs/programs.html',
                               programs=programs, title='Programs',
                               heading='Programs')


@programs_bp.route('/programs/<int:id>', methods=['GET', 'POST'])
@login_required
def change_status(id):
    program = Program.query.filter_by(id=id).first_or_404()
    if program.active is True:
        program.active = False
        flash('Program successfully deactivated.', 'success')
    else:
        program.active = True
        flash('Program successfully activated.', 'success')
    db.session.commit()
    return redirect(url_for('programs_bp.view_programs'))

boar/program/views.py
# views for programs

from boar import app, db
from flask import flash, render_template, redirect, url_for
from flask_login import login_required, current_user
from ..models import Program
from .forms import ProgramForm
from ..tables import Programs


@app.route('/program/new', methods=['GET', 'POST'])
@login_required
def new_program():
    """
    Add a new program
    """
    form = ProgramForm()
    if form.validate_on_submit():
        program = Program(name=form.name.data,
                          organization_id=current_user.organization_id)
        db.session.add(program)
        db.session.commit()
        flash('Program added successfully!')
        return redirect(url_for('index'))
    return render_template('/programs/new_program.html', form=form,
                           title='New Program', heading='New Program')


@app.route('/programs', methods=['GET', 'POST'])
@login_required
def view_programs():
    """
    Displays a table with all active programs.
    """
    programs = Program.query.order_by(Program.name).filter(
        Program.organization_id == current_user.organization_id).all()
        # Program.active == 1).all()
    if not programs:
        flash('No programs found!')
        return redirect(url_for('index'))
    else:
        table = Programs(programs)
        return render_template('/programs/programs.html',
                               table=table, title='Programs',
                               heading='Programs', programs=programs)


@app.route('/programs/<int:id>', methods=['GET', 'POST'])
@login_required
def deactivate(id):
    program = Program.query.filter(Program.id == id).first_or_404()
    program.active = 0
    db.session.commit()
    flash('Program successfully deactived.')
    return redirect(url_for('view_programs'))

boar/views/program.py
# program.py

from boar import app, db
from flask import flash, render_template, redirect, url_for
from flask_login import login_required, current_user
from ..models import Program
from ..forms import ProgramForm
from ..tables import Programs


@app.route('/program/new', methods=['GET', 'POST'])
@login_required
def new_program():
    """
    Add a new program
    """
    form = ProgramForm()
    if form.validate_on_submit():
        program = Program(name=form.name.data,
                          organization_id=current_user.organization_id)
        db.session.add(program)
        db.session.commit()
        flash('Program added successfully!')
        return redirect(url_for('index'))
    return render_template('/forms/program.html', form=form,
                           title='New Program', heading='New Program')


@app.route('/programs', methods=['GET', 'POST'])
@login_required
def view_programs():
    programs = Program.query.order_by(Program.name).filter(
        Program.organization_id == current_user.organization_id).all()
        # Program.active == 1).all()
    if not programs:
        flash('No programs found!')
        return redirect(url_for('index'))
    else:
        table = Programs(programs)
        return render_template('/programs_table.html', table=table,
                               title='Programs', heading='Programs',
                               programs=programs)


@app.route('/programs/<int:id>', methods=['GET', 'POST'])
@login_required
def deactivate(id):
    program = Program.query.filter(Program.id == id).first_or_404()
    program.active = 0
    db.session.commit()
    flash('Program successfully deactived.')
    return redirect(url_for('view_programs'))

boar/templates/programs/new_program.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">{% block heading %}{{ heading }}{% endblock %}</legend>
        <div class="form-group">
          {{ form.name.label(class="form-control-label") }}
          {{ form.name(class="form-control") }}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
  </div>
{% endblock content %}

boar/templates/programs/programs.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<h1>{% block heading %}{{ heading }}{% endblock %}</h1>
<div class="content-section">
  <table id="programs_table" class="table table-hover">
  <thead>
      <tr>
          <th>Name</th>
          <th>Status</th>
          <th>Activate/Deactivate</th>
      </tr>
  </thead>
  <tbody>
    {% for program in programs %}
      <tr>
          <td style="padding: 15px; text-align: left;">{{ program.name }}</td>
          {% if program.active %}
          <td style="padding: 15px; text-align: left;" class="text-success">{{ program.active }}</p></td>
          <td style="padding: 15px; text-align: left;"><a href="{{ url_for('programs_bp.change_status', id=program.id) }}" class="table-link">Deactivate</a></td>
          {% else %}
          <td style="padding: 15px; text-align: left;" class="text-danger">{{ program.active }}</p></td>
          <td style="padding: 15px; text-align: left;"><a href="{{ url_for('programs_bp.change_status', id=program.id) }}" class="table-link">Activate</a></td>
          {% endif %}
      </tr>
    {% endfor %}
  </tbody>
  </table>
</div>
{% endblock content %}