boar/user/routes.py
# routes for users

from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from boar import db
from boar.models import Organization, User
from boar.user.forms import (LoginForm, OrganizationForm, RegistrationForm,
                             RequestResetForm, ResetPasswordForm,
                             UpdateAccountForm)
from boar.user.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    """
    Registers a user.

    Two forms are used because users belong to an organization, which is a
    separate model.
    """
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    registration_form = RegistrationForm()
    organization_form = OrganizationForm()
    if registration_form.validate_on_submit():
        user = User(username=registration_form.username.data,
                    email=registration_form.email.data,
                    first_name=registration_form.first_name.data,
                    last_name=registration_form.last_name.data)
        user.set_password(registration_form.password.data)
        user.set_organization(organization_form.name.data)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in.',
              'success')
        return redirect(url_for('users.login'))
    return render_template('/user/register.html', title='Register',
                           registration_form=registration_form,
                           organization_form=organization_form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
            return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash(f'You have logged in!', 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash('Invalid username or password', 'danger')
            return redirect(url_for('users.login'))
    return render_template('/user/login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route('/user/<username>', methods=['GET', 'POST'])
@login_required
def account(username):
    """
    Renders a profile page for the user from where they can also
    their profile.
    """
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.profile_photo = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    profile_photo = url_for('static',
                            filename='images/' + current_user.profile_photo)
    return render_template('/user/account.html', title='Account',
                           profile_photo=profile_photo, form=form)


@users.route('/organization/<int:id>')
@login_required
def organization(id):
    """
    Renders a profile page for the user's organization.
    """
    organization = Organization.query.get_or_404(id)
    return render_template('/user/organization.html',
                           organization=organization)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to\
              reset your password.', 'info')
    return render_template('/user/reset_request.html', title='Reset Password',
                           form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        db.session.commit()
        flash('Your password has been updated! You are now able to log in.',
              'success')
        return redirect(url_for('login'))
    return render_template('/user/reset_token.html', title='Rset Password',
                           form=form)

boar/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='custom.css') }}" />

    {% if title %}
      <title>{{ title }} - Boar</title>
    {% else %}
      <title>Boar</title>
    {% endif %}
  </head>
  <body>
    <!-- Navigation Bar -->
      <nav class="navbar navbar-expand-md fixed-top">
      <div class="container">
        <a class="navbar-brand mr-4" href="/">Boar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <ul class="navbar-nav mr-auto">
              <li class="dropdown">
                <a class="nav-item nav-link dropdown-toggle" href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Bookings
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <li><a class="dropdown-item nav-item nav-link" href="{{ url_for('booking_bp.new_booking') }}">New Booking</a></li>
                  <li><a class="dropdown-item nav-item nav-link" href="{{ url_for('booking_bp.list_bookings') }}">Bookings</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a class="nav-item nav-link dropdown-toggle" href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Distributors
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <li><a class="nav-item nav-link" href="{{ url_for('distributors_bp.new_distributor') }}">New Distributor</a></li>
                  <li><a class="nav-item nav-link" href="{{ url_for('distributors_bp.list_distributors') }}">Distributors</a></li>
                </ul>
              </li>
              <li class="dropdown">
                <a class="nav-item nav-link dropdown-toggle" href="#" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Programs
                </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <li><a class="nav-item nav-link" href="{{ url_for('programs_bp.new_program') }}">New Program</a></li>
                  <li><a class="nav-item nav-link" href="{{ url_for('programs_bp.view_programs') }}">View Programs</a></li>
                </ul>
              </ul>
            </div>
            <!-- Navbar Right Side-->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="{{ url_for('users.account', username=current_user.username) }}">Account</a>
              <a class="nav-item nav-link" href="{{ url_for('users.organization', id=current_user.organization_id) }}">Organization</a>
              <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
              <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
              <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
      <main role="main" class="container">
        <div class="row">
          <div>
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class='alert alert-{{ category }}'>
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock content %}
          </div>
        </div>
      </main>

      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

boar/templates/delete_booking.html
{% extends 'base.html' %}
{% block title %}Delete Booking - Boar{% endblock %}
{% block content %}

<h2>Delete Booking</h2>

{% from "_formhelpers.html" import render_field  %}
<form method=post>
  <dl>
    {{ render_field(form.distributor) }}
    {{ render_field(form.film) }}
    {{ render_field(form.program) }}
    {{ render_field(form.guarantee) }}
    {{ render_field(form.percentage) }}
    {{ render_field(form.start_date) }}
    {{ render_field(form.end_date) }}
    {{ render_field(form.gross) }}
  </dl>
  <p><input type=submit value=Delete /></p>
</form>

<p><a href="{{ url_for('.open_bookings') }}">Go back</a></p>

<p><a href="{{ url_for('.index') }}">Cancel</a></p>

{% endblock %}

boar/templates/delete_distributor.html
{% extends 'base.html' %}
{% block title %}Delete Distributor - Boar{% endblock %}

{% block content %}

<h2>Delete Distributor</h2>

{% from "_formhelpers.html" import render_field  %}
<form method=post>
  <dl>
    {{ render_field(form.company) }}
    {{ render_field(form.payee) }}
    {{ render_field(form.address1) }}
    {{ render_field(form.address2) }}
    {{ render_field(form.city) }}
    {{ render_field(form.state) }}
    {{ render_field(form.zip) }}
  </dl>
  <p><input type=submit value=Delete /></p>
</form>

<p><a href="{{ url_for('.open_bookings') }}">Go back</a></p>

<p><a href="{{ url_for('.index') }}">Cancel</a></p>

{% endblock %}

boar/templates/edit_distributor.html
{% extends 'base.html' %}
{% block title %}Edit Distributor - Boar{% endblock %}
{% block content %}

<h2>Edit Distributor</h2>

{% from "_formhelpers.html" import render_field  %}
<form method=post>
  <dl>
    {{ render_field(form.company) }}
    {{ render_field(form.payee) }}
    {{ render_field(form.address1) }}
    {{ render_field(form.address2) }}
    {{ render_field(form.city) }}
    {{ render_field(form.state) }}
    {{ render_field(form.zip) }}
  </dl>
  <p><input type=submit value=Submit /></p>
</form>

<p><a href="{{ url_for('.open_bookings') }}">Go back</a></p>

<p><a href="{{ url_for('.index') }}">Cancel</a></p>

{% endblock %}

boar/templates/enter_payment.html
{% extends 'base.html' %}
{% block title %}New Payment - Boar{% endblock %}
{% block content %}

<h2>New Payment</h2>

{% from "_formhelpers.html" import render_field  %}
<form method=post>
  <dl>
    {{ render_field(form.booking) }}
    {{ render_field(form.date) }}
    {{ render_field(form.check_number) }}
    {{ render_field(form.amount) }}
  </dl>
  <p><input type=submit value=Submit /></p>
</form>

<p><a href="{{ url_for('.open_bookings') }}">Go back</a></p>

<p><a href="{{ url_for('.index') }}">Cancel</a></p>

{% endblock %}

boar/templates/index.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
  <div class="content-section">
    {% if current_user.is_authenticated %}
    <h1>Welcome, {{ current_user.first_name }}!</h1>
    {% else %}
    <h1>Welcome to Boar.</h1>
      <p>This web app streamlines the process for tracking box office receipts and payments.</p>
      <p>Sign up <a href="{{ url_for('users.register') }}">here</a></p>
      <p>If you already have an account, log in <a href="{{ url_for('users.login') }}">here</a>.</p>
    {% endif %}
  </div>
{% endblock content %}

boar/templates/new_booking.html
{% extends 'base.html' %}
{% block title %}New Booking - Boar{% endblock %}
{% block content %}

<h2>New Booking</h2>

{% from "_formhelpers.html" import render_field  %}
<form method=post>
  <dl>
    {{ render_field(form.distributor) }}
    {{ render_field(form.film) }}
    {{ render_field(form.program) }}
    {{ render_field(form.guarantee) }}
    {{ render_field(form.percentage) }}
    {{ render_field(form.start_date) }}
    {{ render_field(form.end_date) }}
    {{ render_field(form.gross) }}
  </dl>
  <p><input type=submit value=Submit /></p>
</form>

<a href="{{ url_for('.index') }}">Cancel</a>

{% endblock %}

boar/templates/new_distributor.html
{% extends 'base.html' %}
{% block title %}New Distributor - Boar{% endblock %}

{% block content %}

<h2>New Distributor</h2>

{% from "_formhelpers.html" import render_field  %}
<form method=post>
  <dl>
    {{ render_field(form.company) }}
    {{ render_field(form.payee) }}
    {{ render_field(form.address1) }}
    {{ render_field(form.address2) }}
    {{ render_field(form.city) }}
    {{ render_field(form.state) }}
    {{ render_field(form.zip) }}
  </dl>
  <p><input type=submit value=Submit /></p>
</form>

<a href="{{ url_for('.index') }}">Cancel</a>

{% endblock %}

boar/templates/table.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
  <h1>{% block heading %}{{ heading }}{% endblock %}</h1>
  <div>
    {{ table }}
  </div>
{% endblock content %}

boar/templates/update_booking.html
{% extends 'base.html' %}
{% block title %}Update Booking - Boar{% endblock %}
{% block content %}

<h2>Update Booking</h2>

{% from "_formhelpers.html" import render_field  %}
<form method=post>
  <dl>
    {{ render_field(form.distributor) }}
    {{ render_field(form.film) }}
    {{ render_field(form.program) }}
    {{ render_field(form.guarantee) }}
    {{ render_field(form.percentage) }}
    {{ render_field(form.start_date) }}
    {{ render_field(form.end_date) }}
    {{ render_field(form.gross) }}
  </dl>
  <p><input type=submit value=Submit /></p>
</form>

<p><a href="{{ url_for('.open_bookings') }}">Go back</a></p>

<p><a href="{{ url_for('.index') }}">Cancel</a></p>


{% endblock %}