boar/booking/forms.py
# forms for bookings

from datetime import datetime
from flask_wtf import FlaskForm
from wtforms import IntegerField, StringField, SubmitField
from wtforms.fields.html5 import DateField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import InputRequired
from boar.booking.utils import query_distributor, query_program


class BookingForm(FlaskForm):
    distributor = QuerySelectField(query_factory=query_distributor,
                                   allow_blank=False, get_label='company')
    film = StringField('Film', validators=[InputRequired()])
    program = QuerySelectField(query_factory=query_program,
                               allow_blank=False, get_label='name')
    guarantee = IntegerField('Guarantee', default=0)
    percentage = IntegerField('Percentage', default=35)
    start_date = DateField('Start Date', default=datetime.utcnow)
    end_date = DateField('End Date', default=datetime.utcnow)
    gross = IntegerField('Gross', default=0)
    submit = SubmitField('Submit')

boar/bookings/forms.py
# forms for bookings

from datetime import datetime
from flask_wtf import FlaskForm
from wtforms import DecimalField, StringField, SubmitField
from wtforms.fields.html5 import DateField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import InputRequired
from boar.bookings.utils import query_distributors, query_programs


class BookingForm(FlaskForm):
    film = StringField('Film', validators=[InputRequired()])
    start_date = DateField('Start Date', default=datetime.utcnow)
    end_date = DateField('End Date', default=datetime.utcnow)
    guarantee = DecimalField('Minimum Guarantee', default=0)
    percentage = DecimalField('Percentage', default=35)
    gross = DecimalField('Gross', default=0)
    program = QuerySelectField(query_factory=query_programs,
                               allow_blank=False, get_label='name')
    distributor = QuerySelectField(query_factory=query_distributors,
                                   allow_blank=True, get_label='company')
    submit = SubmitField('Submit')

boar/booking/views.py
# views for bookings

from boar import app, db
from flask import flash, redirect, render_template, url_for
from flask_login import current_user, login_required
from ..models import Booking
from .forms import BookingForm
from ..tables import Bookings


@app.route('/booking/new', methods=['GET', 'POST'])
@login_required
def new_booking():
    """
    Add a new booking
    """
    form = BookingForm()
    if form.validate_on_submit():
        booking = Booking(distributor=form.distributor.data,
                          film=form.film.data,
                          program=form.program.data,
                          guarantee=form.guarantee.data,
                          percentage=form.percentage.data,
                          start_date=form.start_date.data,
                          end_date=form.end_date.data,
                          gross=form.gross.data,
                          organization_id=current_user.organization_id)
        db.session.add(booking)
        db.session.commit()
        flash('Booking entered.', 'success')
        return redirect(url_for('open_bookings'))
    return render_template('/booking/booking.html', form=form,
                           title='New Booking', legend='New Booking')


@app.route('/open_bookings')
@login_required
def open_bookings():
    bookings = Booking.query.order_by(
        Booking.start_date).filter(
        Booking.settled == 0,
        Booking.organization_id == current_user.organization_id).all()
    if not bookings:
        flash('No open bookings found.', 'warning')
        return redirect(url_for('index'))
    else:
        table = Bookings(bookings)
        return render_template('/table.html', table=table,
                               title='Open Bookings', heading='Open Bookings')


@app.route('/booking/update/<int:id>', methods=['GET', 'POST'])
@login_required
def update_booking(id):
    # check if current user belongs to booking's organization and if not,
    # render the 404 page because the query returns None
    booking = Booking.query.filter(
              Booking.id == id,
              Booking.organization_id == current_user.organization_id
              ).first_or_404()
    form = BookingForm(obj=booking)
    if form.validate_on_submit():
        booking.distributor = form.distributor.data
        booking.film = form.film.data
        booking.program = form.program.data
        booking.guarantee = form.guarantee.data
        booking.percentage = form.percentage.data
        booking.start_date = form.start_date.data
        booking.end_date = form.end_date.data
        booking.gross = form.gross.data
        db.session.commit()
        flash('Booking updated.', 'success')
        return redirect(url_for('open_bookings'))
    return render_template('/booking/booking.html', form=form,
                           title='Update Booking', legend='Update Booking')


@app.route('/booking/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_booking(id):
    booking = Booking.query.filter(Booking.id == id).first()
    db.session.delete(booking)
    db.session.commit()
    flash('Booking deleted.', 'success')
    return redirect(url_for('open_bookings'))

boar/bookings/routes.py
# routes for bookings

import decimal
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user, login_required
from boar import db
from boar.models import Booking
from boar.bookings.forms import BookingForm
from boar.bookings.utils import results

booking_bp = Blueprint('booking_bp', __name__)


@booking_bp.route('/booking/new', methods=['GET', 'POST'])
@login_required
def new_booking():
    """
    Adds a new booking
    """
    form = BookingForm()
    if form.validate_on_submit():
        booking = Booking(film=form.film.data,
                          start_date=form.start_date.data,
                          end_date=form.end_date.data,
                          guarantee=decimal.Decimal(form.guarantee.data),
                          percentage=decimal.Decimal(form.percentage.data),
                          gross=decimal.Decimal(form.gross.data),
                          program=form.program.data,
                          distributor=form.distributor.data,
                          organization_id=current_user.organization_id)
        db.session.add(booking)
        db.session.commit()
        flash('Booking successfully created.', 'success')
        return redirect(url_for('booking_bp.list_bookings'))
    return render_template('/bookings/new_booking.html', form=form,
                           title='New Booking', legend='New Booking')


@booking_bp.route('/booking/update/<int:id>', methods=['GET', 'POST'])
@login_required
def update_booking(id):
    """
    Updates a booking
    """
    # check if current user belongs to booking's organization and if not,
    # render the 404 page because the query returns None
    booking = Booking.query.filter_by(
        id=id, organization_id=current_user.organization_id).first_or_404()
    form = BookingForm(obj=booking)
    if form.validate_on_submit():
        form.populate_obj(booking)
        db.session.commit()
        flash('Booking successfully updated.', 'success')
        return redirect(url_for('booking_bp.list_bookings'))
    return render_template('/bookings/new_booking.html', form=form,
                           title='Update Booking', legend='Update Booking')


@booking_bp.route('/booking/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_booking(id):
    """
    Deletes a booking
    """
    booking = Booking.query.filter_by(id=id).first()
    db.session.delete(booking)
    db.session.commit()
    flash('Booking successfully deleted.', 'success')
    return redirect(url_for('booking_bp.list_bookings'))


@booking_bp.route('/bookings')
@login_required
def list_bookings():
    """
    Renders a template with a table containing all unsettled bookings
    """
    bookings = Booking.query.order_by(
        Booking.start_date).filter_by(
                        organization_id=current_user.organization_id).all()
    if not bookings:
        flash('No open bookings found.', 'warning')
        return redirect(url_for('main.index'))
    else:
        return render_template('/bookings/booking_table.html',
                               bookings=bookings, title='Bookings',
                               heading='Bookings')


@booking_bp.route('/booking/results/<int:id>', methods=['GET'])
@login_required
def booking_results(id):
    """
    Renders a template containing a booking's box office performance.
    """
    finances = results(id)
    if not finances:
        flash('No booking found!')
        return redirect(url_for('booking_bp.list_bookings'))
    else:
        return render_template('/bookings/results.html', finances=finances,
                               title='Results', heading='Results')

boar/payment/routes.py
# routes for payments

from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import login_required
from boar import db
from boar.models import Booking, Payment
from boar.payment.forms import PaymentForm

payments_bp = Blueprint('payments_bp', __name__)


@payments_bp.route('/payment/new/<int:id>', methods=['GET', 'POST'])
@login_required
def new_payment(id):
    """
    Add a payment
    """
    booking = Booking.query.filter(Booking.id == id).first()
    form = PaymentForm(obj=booking)
    if form.validate_on_submit():
        payment = Payment(booking=booking,
                          date=form.date.data,
                          check_number=form.check_number.data,
                          amount=form.amount.data)
        db.session.add(payment)
        db.session.commit()
        flash('Payment entered successfully!')
        return redirect(url_for('booking_bp.list_bookings'))
    return render_template('/payments/new_payment.html', form=form,
                           title='New Payment', legend='New Payment')


@payments_bp.route('/payments/<int:id>')
@login_required
def view_payments(id):
    """
    View payments associated with booking
    """
    payments = Payment.query.filter(Payment.booking_id == id).all()
    if not payments:
        flash('No payments found!', 'warning')
        return redirect(url_for('booking_bp.list_bookings'))
    else:
        return render_template('/payments/payments_table.html',
                               payments=payments, title='Payments',
                               heading='Payments')

boar/results/views.py
# results.py

from boar import app
from flask import flash, redirect, render_template, url_for
from flask_login import login_required
from ..models import Booking
from ..tables import Results


@app.route('/results/<int:id>')
@login_required
def view_results(id):
    """
    View results.
    """
    booking = Booking.query.filter(Booking.id == id).first()

    film = booking.film
    percentage = booking.percentage
    guarantee = booking.guarantee
    gross = booking.gross

    # overage
    def overage(percentage, guarantee, gross):
        if (percentage / 100) * gross > guarantee:
            overage = (percentage / 100) * gross - guarantee
            return round(overage, 2)
        else:
            overage = 0
            return overage

    overage = overage(percentage, guarantee, gross)

    # total owed
    def total_owed(guarantee, overage):
        owed = guarantee + overage
        return owed

    owed = total_owed(guarantee, overage)

    # net
    def net(gross, owed):
        if gross == 0:
            net = 0
        else:
            net = gross - owed
        return net

    net = net(gross, owed)

    finances = [{'film': film, 'gross': gross, 'guarantee': guarantee,
                 'overage': overage, 'owed': owed, 'net': net}]

    if not booking:
        flash('No booking found!')
        return redirect(url_for('open_bookings'))
    else:
        table = Results(finances)
        return render_template('table.html', table=table,
                               title='Results', heading='Results')

boar/views/booking.py
# booking.py

from boar import app, db
from flask import flash, redirect, render_template, url_for
from flask_login import current_user, login_required
from ..models import Booking
from ..forms import BookingForm
from ..tables import Bookings


@app.route('/booking/new', methods=['GET', 'POST'])
@login_required
def new_booking():
    """
    Add a new booking
    """
    form = BookingForm()
    if form.validate_on_submit():
        booking = Booking(distributor=form.distributor.data,
                          film=form.film.data,
                          program=form.program.data,
                          guarantee=form.guarantee.data,
                          percentage=form.percentage.data,
                          start_date=form.start_date.data,
                          end_date=form.end_date.data,
                          gross=form.gross.data,
                          organization_id=current_user.organization_id)
        db.session.add(booking)
        db.session.commit()
        flash('Booking added successfully!')
        return redirect(url_for('open_bookings'))
    return render_template('/forms/booking.html', form=form,
                           title='New Booking', heading='New Booking')


@app.route('/open_bookings')
@login_required
def open_bookings():
    bookings = Booking.query.order_by(
        Booking.start_date).filter(
        Booking.settled == 0,
        Booking.organization_id == current_user.organization_id).all()
    if not bookings:
        flash('No open bookings found!')
        return redirect(url_for('index'))
    else:
        table = Bookings(bookings)
        return render_template('/table.html', table=table,
                               title='Open Bookings', heading='Open Bookings')


@app.route('/booking/update/<int:id>', methods=['GET', 'POST'])
@login_required
def update_booking(id):
    # check if current user belongs to booking's organization and if not,
    # render the 404 page because the query returns None
    booking = Booking.query.filter(
              Booking.id == id,
              Booking.organization_id == current_user.organization_id
              ).first_or_404()
    form = BookingForm(obj=booking)
    if form.validate_on_submit():
        booking.distributor = form.distributor.data
        booking.film = form.film.data
        booking.program = form.program.data
        booking.guarantee = form.guarantee.data
        booking.percentage = form.percentage.data
        booking.start_date = form.start_date.data
        booking.end_date = form.end_date.data
        booking.gross = form.gross.data
        db.session.commit()
        flash('Booking updated successfully!')
        return redirect(url_for('open_bookings'))
    return render_template('/forms/booking.html', form=form,
                           title='Update Booking', heading='Update Booking')


@app.route('/booking/delete/<int:id>', methods=['GET', 'POST'])
@login_required
def delete_booking(id):
    booking = Booking.query.filter(Booking.id == id).first()
    db.session.delete(booking)
    db.session.commit()
    flash('Booking successfully deleted!')
    return redirect(url_for('open_bookings'))

boar/views/results.py
# results.py

from boar import app
from flask import flash, redirect, render_template, url_for
from flask_login import login_required
from ..models import Booking
from ..tables import Results


@app.route('/results/<int:id>')
@login_required
def view_results(id):
    """
    View results.
    """
    booking = Booking.query.filter(Booking.id == id).first()

    film = booking.film
    percentage = booking.percentage
    guarantee = booking.guarantee
    gross = booking.gross

    # overage
    def overage(percentage, guarantee, gross):
        if (percentage / 100) * gross > guarantee:
            overage = (percentage / 100) * gross - guarantee
            return round(overage, 2)
        else:
            overage = 0
            return overage

    overage = overage(percentage, guarantee, gross)

    # total owed
    def total_owed(guarantee, overage):
        owed = guarantee + overage
        return owed

    owed = total_owed(guarantee, overage)

    # net
    def net(gross, owed):
        if gross == 0:
            net = 0
        else:
            net = gross - owed
        return net

    net = net(gross, owed)

    finances = [{'film': film, 'gross': gross, 'guarantee': guarantee,
                 'overage': overage, 'owed': owed, 'net': net}]

    if not booking:
        flash('No booking found!')
        return redirect(url_for('open_bookings'))
    else:
        table = Results(finances)
        return render_template('table.html', table=table,
                               title='Results', heading='Results')

boar/templates/bookings/booking_table.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<h1>{% block heading %}{{ heading }}{% endblock %}</h1>
<div class="content-section">
  <table id="bookings_table" class="table table-hover">
  <thead>
      <tr>
          <th>Film</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th>Guarantee</th>
          <th>Percentage</th>
          <th>Gross</th>
          <th>Settled</th>
          <th>Program</th>
          <th>Distributor</th>
          <th>Results</th>
          <th>Add Payment</th>
          <th>View Payments</th>
          <th>Update</th>
          <th>Delete</th>
      </tr>
  </thead>
  <tbody>
    {% for booking in bookings %}
      <tr>
          <td style="padding: 15px; text-align: left;">{{ booking.film }}</td>
          <td style="padding: 15px; text-align: left;">{{ booking.start_date|datetimeformat }}</td>
          <td style="padding: 15px; text-align: left;">{{ booking.end_date|datetimeformat }}</td>
          <td style="padding: 15px; text-align: right;">{{ booking.guarantee|round(2, 'common')|format_currency }}</td>
          <td style="padding: 15px; text-align: right;">{{ booking.percentage|format_percentage }}</td>
          <td style="padding: 15px; text-align: right;">{{ booking.gross|round(2, 'common')|format_currency }}</td>
          {% if booking.settled %}
          <td style="padding: 15px; text-align: left;" class="text-success">{{ booking.settled }}</td>
          {% else %}
          <td style="padding: 15px; text-align: left;" class="text-danger">{{ booking.settled }}</td>
          {% endif %}
          <td style="padding: 15px; text-align: left">{{ booking.program }}</td>
          <td style="padding: 15px; text-align: left">{{ booking.distributor }}</td>
          <td style="padding: 15px; text-align: left;"><a href="{{ url_for('booking_bp.booking_results', id=booking.id) }}" class="table-link">Results</a></td>
          <td style="padding: 15px; text-align: left;"><a href="{{ url_for('payments_bp.new_payment', id=booking.id) }}" class="table-link">Add Payment</a></td>
          <td style="padding: 15px; text-align: left;"><a href="{{ url_for('payments_bp.view_payments', id=booking.id) }}" class="table-link">View Payment</a></td>
          <td style="padding: 15px; text-align: left;"><a href="{{ url_for('booking_bp.update_booking', id=booking.id) }}" class="table-link">Update</a></td>
          <td style="padding: 15px; text-align: left;"><a href="{{ url_for('booking_bp.delete_booking', id=booking.id) }}" class="table-link">Delete</a></td>
          </td>
      </tr>
    {% endfor %}
  </tbody>
  </table>
</div>
{% endblock content %}

boar/templates/bookings/new_booking.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">{% block legend %}{{ legend }}{% endblock %}</legend>
        <!-- Film -->
        <div class="form-group">
          {{ form.film.label(class="form-control-label") }}
          {% if form.film.errors %}
            {{ form.film(class="form-control is-invalid") }}
            <div class="invalid-feedback">
            {% for error in form.film.errors %}
              <span>{{ error }}</span>
            {% endfor %}
            </div>
          {% else %}
            {{ form.film(class="form-control") }}
          {% endif %}
        </div>
        <!-- Start Date -->
        <div class="form-group">
          {{ form.start_date.label(class="form-control-label") }}
          {% if form.start_date.errors %}
            {{ form.start_date(class="form-control is-invalid") }}
            <div class="invalid-feedback">
            {% for error in form.start_date.errors %}
              <span>{{ error }}</span>
            {% endfor %}
            </div>
          {% else %}
            {{ form.start_date(class="form-control") }}
          {% endif %}
        </div>
        <!-- End Date -->
        <div class="form-group">
          {{ form.end_date.label(class="form-control-label") }}
          {% if form.end_date.errors %}
            {{ form.end_date(class="form-control is-invalid") }}
            <div class="invalid-feedback">
            {% for error in form.end_date.errors %}
              <span>{{ error }}</span>
            {% endfor %}
            </div>
          {% else %}
            {{ form.end_date(class="form-control") }}
          {% endif %}
        </div>
        <!-- Guarantee -->
        <div class="form-group">
          {{ form.guarantee.label(class="form-control-label") }}
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">$</span>
            </div>
          {% if form.guarantee.errors %}
            {{ form.guarantee(class="form-control is-invalid") }}
            <div class="invalid-feedback">
            {% for error in form.guarantee.errors %}
              <span>{{ error }}</span>
            {% endfor %}
            </div>
          {% else %}
            {{ form.guarantee(class="form-control") }}
          {% endif %}
          </div>
        </div>
        <!-- Percentage -->
        <div class="form-group">
          {{ form.percentage.label(class="form-control-label") }}
          <div class="input-group">
            {% if form.percentage.errors %}
              {{ form.percentage(class="form-control is-invalid") }}
              <div class="invalid-feedback">
              {% for error in form.percentage.errors %}
                <span>{{ error }}</span>
              {% endfor %}
              </div>
            {% else %}
              {{ form.percentage(class="form-control") }}
            {% endif %}
            <div class="input-group-append">
              <span class="input-group-text">%</span>
            </div>
          </div>
        </div>
        <!-- Gross -->
        <div class="form-group">
          {{ form.gross.label(class="form-control-label") }}
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text">$</span>
            </div>
          {% if form.gross.errors %}
            {{ form.gross(class="form-control is-invalid") }}
            <div class="invalid-feedback">
            {% for error in form.gross.errors %}
              <span>{{ error }}</span>
            {% endfor %}
            </div>
          {% else %}
            {{ form.gross(class="form-control") }}
          {% endif %}
          </div>
        </div>
        <!-- Program -->
        <div class="form-group">
          {{ form.program.label(class="form-control-label") }}
          {% if form.program.errors %}
            {{ form.program(class="form-control is-invalid") }}
            <div class="invalid-feedback">
            {% for error in form.program.errors %}
              <span>{{ error }}</span>
            {% endfor %}
            </div>
          {% else %}
            {{ form.program(class="form-control") }}
          {% endif %}
        </div>
        <!-- Distributor -->
        <div class="form-group">
          {{ form.distributor.label(class="form-control-label") }}
          {% if form.distributor.errors %}
            {{ form.distributor(class="form-control is-invalid") }}
            <div class="invalid-feedback">
            {% for error in form.distributor.errors %}
              <span>{{ error }}</span>
            {% endfor %}
            </div>
          {% else %}
            {{ form.distributor(class="form-control") }}
          {% endif %}
        </div>
      </fieldset>
      <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
      </div>
    </form>
  </div>
{% endblock content %}

boar/templates/bookings/results.html
{% extends 'base.html' %}
{% block title %}{{ title }}{% endblock title %}
{% block content %}
<h1>{% block heading %}{{ heading }}{% endblock heading %}</h1>
<div class="content-section">
  <table id="results_table" class="table table-hover">
    <thead>
      <tr>
        <th>Film</th>
        <th>Gross</th>
        <th>Guarantee</th>
        <th>Overage</th>
        <th>Owed</th>
        <th>Net</th>
      </tr>
    </thead>
    </tbody>
    {% for item in finances %}
    <tr>
      <td style="padding: 15px; text-align: left;"> {{ item['film'] }}</td>
      <td style="padding: 15px; text-align: right;"> {{ item['gross']|round(2, 'common')|format_currency }}</td>
      <td style="padding: 15px; text-align: right;"> {{ item['guarantee']|round(2, 'common')|format_currency }}</td>
      <td style="padding: 15px; text-align: right;"> {{ item['overage']|round(2, 'common')|format_currency }}</td>
      <td style="padding: 15px; text-align: right;"> {{ item['owed']|round(2, 'common')|format_currency }}</td>
      <td style="padding: 15px; text-align: right;"> {{ item['net']|round(2, 'common')|format_currency }}</td>
    </tr>
    {% endfor %}
  </table>
</div>
{% endblock content %}